name: check-links

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check all files have a corresponding link on the README.md
        run: |
          $GITHUB_WORKSPACE/scripts/check-links.sh
